"""create licitacoes table

Revision ID: 9ff42e3b771f
Revises:
Create Date: 2026-09-08 16:01:20.746784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ff42e3b771f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('licitacoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('cidade', sa.String(length=100), nullable=False),
    sa.Column('valor_estimado', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('modalidade', sa.String(length=50), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_licitacoes_cidade'), 'licitacoes', ['cidade'], unique=False)
    op.create_index(op.f('ix_licitacoes_modalidade'), 'licitacoes', ['modalidade'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_licitacoes_modalidade'), table_name='licitacoes')
    op.drop_index(op.f('ix_licitacoes_cidade'), table_name='licitacoes')
    op.drop_table('licitacoes')
    # ### end Alembic commands ###
